version: '3.8'

services:
  landing-page:
    image: imagesnexaconnect/landing-page:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
